dist: xenial
language: python
python: 
  - "3.6"
env:
  global:
    - PATH=./pandoc-2.7.1/bin/:$PATH
install:
  - pip install -r requirements.txt
  - wget https://github.com/jgm/pandoc/releases/download/2.7.1/pandoc-2.7.1-linux.tar.gz
  - tar -xf pandoc-2.7.1-linux.tar.gz
script:
  - which pandoc
  - pandoc -v
  - cd report && make
  - pdfinfo merged.pdf
  - PYTHONPATH=./ pytest -v --capture=no
addons:
  apt:
    packages:
      - pandoc
      - pandoc-citeproc
      - texlive
      - lmodern
      - poppler-utils
      - ghostscript
