dist: xenial
language: python
python: 
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest -v
  - make
addons:
  apt:
    packages:
      - pandoc
      - pandoc-citeproc
      - texlive
      - lmodern
      - ghostscript
