dist: xenial
language: python
python: 
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - PYTHONPATH=./ pytest -v --capture=no
  - cd report && make
  - pdfinfo merged.pdf
addons:
  apt:
    packages:
      - pandoc
      - pandoc-citeproc
      - texlive
      - lmodern
      - poppler-utils
      - ghostscript
