dist: xenial
language: python
python: 
  - "3.6"
install:
  - pip install -r requirements.txt
  - wget https://github.com/jgm/pandoc/releases/download/2.7.1/pandoc-2.7.1-linux.tar.gz
  - tar -xf pandoc-2.7.1-linux.tar.gz
  - export PATH=`pwd`/pandoc-2.7.1/bin/:$PATH
script:
  - which pandoc
  - pandoc -v
  - cd report && make
  - pdfinfo report.pdf
  - cd -
  - PYTHONPATH=./ pytest -v --capture=no
  - cd firmware/perftest && make
addons:
  apt:
    packages:
      - pandoc
      - pandoc-citeproc
      - texlive
      - texlive-latex-extra
      - python-pygments
      - lmodern
      - poppler-utils
      - ghostscript
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
