name: microesc
dependencies:
  - python=3.6.*
  - pip=19.0.*
  - numpy=1.17.*
  - matplotlib=3.1.*
  - pandas>=0.23.0
  - scipy>=1.3.0
  - seaborn>=0.9.0
  - scikit-learn>=0.21.1
  - tensorflow>=1.12
  - keras>=2.2.4
  - jupyterlab>=1.1.4
  - pip:
    - soundfile>=0.10
    - librosa>=0.7.*
    - pytest>=5.1.3
